### ISSUE TITLE
Change import of BTM_Plus on README

### ISSUE THREAD

**Issue by ggruenhagen3** [shuzhao-li/BTM#2]
Hi,

I think the code for importing BTM_Plus on the README should be changed from ```from BTM_Plus import BTM_Plus as B2``` to ```from BTM.BTM_Plus import BTM_Plus as B2```.

Thanks,
George

**Comment by lucygarner** [comment]
Yes, agreed.

**Comment by shuzhao-li** [comment]
Updated. Thank you both!
